
experiment:
  name: is_masked_face_head_frozen_bn_coco_from_adamW
  save_dir: tb_logs
  seed: 777
  gpu: [0]
  accelerator: gpu
  comment: ~

  ckpt_callback:
    save_top_k: 3
    monitor: val_bce_loss
    mode: min
  early_stop:
    monitor: val_bce_loss
    mode: min
    patience: 10


training:
  train_fc_only: true
  max_epochs: 200
  opt: Adam
  lr: 0.0001
  weight_decay: 0.00001
  loss: binary_cross_entropy_with_logits
  batch_size: &bs 128
  grad_acc: 1

  scheduler:
    name: ReduceLROnPlateau
    monitor: 'val_bce_loss'
    mode: 'min'
    patience: 3
    factor: 0.1
    min_lr: 0.00000001

  # scheduler:
  #   name: ExponentialLR
  #   monitor: 'train/loss'
  #   mode: 'min'
  #   gamma: 0.94

dataset:
  fgvcx:
    num_classes: 1
    train_list: /data/tasks/versus_test_assingment/data/mask_crops_train.csv
    val_list: /data/tasks/versus_test_assingment/data/mask_crops_val.csv
    test_list: /data/tasks/versus_test_assingment/data/mask_crops_test.csv
    root: /data/tasks/versus_test_assingment/data/mask_crops
    ##crop_fraction: 1.0
    crop_size: 96
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    num_workers: 4
    batch_size: *bs

model:
  unfreeze_modules: ['classifier']
  n_classes: 1
  target_labels: ['without_mask', 'with_mask']
  arch: tf_efficientnet_b0
  ckpt: # /recognition/is_masked_class_train/logs/tb_logs/version_1/checkpoints/epoch.ckpt
  dropout: 0.2
  pretrained: true
  